// <auto-generated>
// Native method imports for SonicKit library.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace SonicKit.Native;

/// <summary>
/// P/Invoke declarations for the native SonicKit library.
/// </summary>
internal static partial class NativeMethods
{
    private const string LibraryName = "sonickit";

    // ============================================
    // Version API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_get_version_string")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_get_version_string();

    [LibraryImport(LibraryName, EntryPoint = "voice_get_version")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_get_version(out int major, out int minor, out int patch);

    // ============================================
    // Denoiser API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_denoiser_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_denoiser_create(int sampleRate, int frameSize, int engineType);

    [LibraryImport(LibraryName, EntryPoint = "voice_denoiser_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_denoiser_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_denoiser_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_denoiser_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_denoiser_reset")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_denoiser_reset(IntPtr handle);

    // ============================================
    // Echo Canceller API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_aec_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_aec_create(int sampleRate, int frameSize, int filterLength);

    [LibraryImport(LibraryName, EntryPoint = "voice_aec_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_aec_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_aec_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_aec_process(IntPtr handle, IntPtr captured, IntPtr playback, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_aec_reset")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_aec_reset(IntPtr handle);

    // ============================================
    // AGC API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_agc_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_agc_create(int sampleRate, int frameSize, int mode, float targetLevel);

    [LibraryImport(LibraryName, EntryPoint = "voice_agc_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_agc_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_agc_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_agc_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_agc_get_gain")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial float voice_agc_get_gain(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_agc_reset")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_agc_reset(IntPtr handle);

    // ============================================
    // VAD API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_vad_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_vad_create(int sampleRate, int mode);

    [LibraryImport(LibraryName, EntryPoint = "voice_vad_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_vad_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_vad_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool voice_vad_process(IntPtr handle, IntPtr samples, int numSamples);

    [LibraryImport(LibraryName, EntryPoint = "voice_vad_get_probability")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial float voice_vad_get_probability(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_vad_reset")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_vad_reset(IntPtr handle);

    // ============================================
    // Resampler API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_resampler_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_resampler_create(int channels, int inRate, int outRate, int quality);

    [LibraryImport(LibraryName, EntryPoint = "voice_resampler_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_resampler_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_resampler_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_resampler_process(IntPtr handle, IntPtr input, int inSamples, IntPtr output, int outCapacity);

    [LibraryImport(LibraryName, EntryPoint = "voice_resampler_reset")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_resampler_reset(IntPtr handle);

    // ============================================
    // DTMF Detector API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_detector_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_dtmf_detector_create(int sampleRate, int frameSize);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_detector_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_dtmf_detector_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_detector_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial byte voice_dtmf_detector_process(IntPtr handle, IntPtr samples, int numSamples);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_detector_get_digits")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_dtmf_detector_get_digits(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_detector_clear")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_dtmf_detector_clear(IntPtr handle);

    // ============================================
    // DTMF Generator API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_generator_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_dtmf_generator_create(int sampleRate, int toneMs, int pauseMs);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_generator_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_dtmf_generator_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_generator_generate_digit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_dtmf_generator_generate_digit(IntPtr handle, byte digit, IntPtr output, int capacity);

    [LibraryImport(LibraryName, EntryPoint = "voice_dtmf_generator_generate_sequence")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_dtmf_generator_generate_sequence(IntPtr handle, IntPtr digits, IntPtr output, int capacity);

    // ============================================
    // Equalizer API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_eq_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_eq_create(int sampleRate, int numBands);

    [LibraryImport(LibraryName, EntryPoint = "voice_eq_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_eq_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_eq_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_eq_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_eq_set_band")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_eq_set_band(IntPtr handle, int band, float frequency, float gainDb, float q);

    [LibraryImport(LibraryName, EntryPoint = "voice_eq_set_master_gain")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_eq_set_master_gain(IntPtr handle, float gainDb);

    // ============================================
    // Compressor API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_compressor_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_compressor_create(int sampleRate, float threshold, float ratio, float attackMs, float releaseMs);

    [LibraryImport(LibraryName, EntryPoint = "voice_compressor_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_compressor_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_compressor_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_compressor_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_compressor_set_threshold")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_compressor_set_threshold(IntPtr handle, float thresholdDb);

    [LibraryImport(LibraryName, EntryPoint = "voice_compressor_set_ratio")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_compressor_set_ratio(IntPtr handle, float ratio);

    // ============================================
    // G.711 Codec API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_g711_encode_alaw")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_g711_encode_alaw(IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_g711_decode_alaw")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_g711_decode_alaw(IntPtr input, IntPtr output, int bytes);

    [LibraryImport(LibraryName, EntryPoint = "voice_g711_encode_ulaw")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_g711_encode_ulaw(IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_g711_decode_ulaw")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_g711_decode_ulaw(IntPtr input, IntPtr output, int bytes);

    // ============================================
    // Audio Buffer API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_buffer_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_buffer_create(int capacity, int channels);

    [LibraryImport(LibraryName, EntryPoint = "voice_buffer_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_buffer_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_buffer_write")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_buffer_write(IntPtr handle, IntPtr data, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_buffer_read")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_buffer_read(IntPtr handle, IntPtr data, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_buffer_available")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_buffer_available(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_buffer_clear")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_buffer_clear(IntPtr handle);

    // ============================================
    // Audio Level API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_level_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_level_create(int sampleRate, int frameSize);

    [LibraryImport(LibraryName, EntryPoint = "voice_level_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_level_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_level_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_level_process(IntPtr handle, IntPtr samples, int numSamples);

    [LibraryImport(LibraryName, EntryPoint = "voice_level_get_db")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial float voice_level_get_db(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_level_get_peak_db")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial float voice_level_get_peak_db(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_level_is_silence")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool voice_level_is_silence(IntPtr handle, float thresholdDb);

    [LibraryImport(LibraryName, EntryPoint = "voice_level_is_clipping")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool voice_level_is_clipping(IntPtr handle);

    // ============================================
    // Audio Mixer API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_mixer_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_mixer_create(int sampleRate, int numInputs, int frameSize);

    [LibraryImport(LibraryName, EntryPoint = "voice_mixer_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_mixer_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_mixer_set_input")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_mixer_set_input(IntPtr handle, int index, IntPtr samples, int numSamples);

    [LibraryImport(LibraryName, EntryPoint = "voice_mixer_set_input_gain")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_mixer_set_input_gain(IntPtr handle, int index, float gain);

    [LibraryImport(LibraryName, EntryPoint = "voice_mixer_mix")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_mixer_mix(IntPtr handle, IntPtr output, int samples);

    // ============================================
    // Jitter Buffer API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_jitter_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_jitter_create(int sampleRate, int frameSizeMs, int minDelayMs, int maxDelayMs);

    [LibraryImport(LibraryName, EntryPoint = "voice_jitter_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_jitter_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_jitter_put")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_jitter_put(IntPtr handle, IntPtr samples, int numSamples, uint timestamp, ushort sequence);

    [LibraryImport(LibraryName, EntryPoint = "voice_jitter_get")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_jitter_get(IntPtr handle, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_jitter_get_delay_ms")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial float voice_jitter_get_delay_ms(IntPtr handle);

    // ============================================
    // Spatial Audio API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_spatial_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_spatial_create(int sampleRate, int frameSize);

    [LibraryImport(LibraryName, EntryPoint = "voice_spatial_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_spatial_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_spatial_set_source_position")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_spatial_set_source_position(IntPtr handle, float x, float y, float z);

    [LibraryImport(LibraryName, EntryPoint = "voice_spatial_set_listener_position")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_spatial_set_listener_position(IntPtr handle, float x, float y, float z);

    [LibraryImport(LibraryName, EntryPoint = "voice_spatial_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_spatial_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    // ============================================
    // HRTF API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_hrtf_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_hrtf_create(int sampleRate);

    [LibraryImport(LibraryName, EntryPoint = "voice_hrtf_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_hrtf_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_hrtf_set_azimuth")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_hrtf_set_azimuth(IntPtr handle, float azimuth);

    [LibraryImport(LibraryName, EntryPoint = "voice_hrtf_set_elevation")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_hrtf_set_elevation(IntPtr handle, float elevation);

    [LibraryImport(LibraryName, EntryPoint = "voice_hrtf_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_hrtf_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    // ============================================
    // Reverb API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_reverb_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_reverb_create(int sampleRate, float roomSize, float damping, float wetLevel, float dryLevel);

    [LibraryImport(LibraryName, EntryPoint = "voice_reverb_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_reverb_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_reverb_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_reverb_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_reverb_set_room_size")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_reverb_set_room_size(IntPtr handle, float roomSize);

    [LibraryImport(LibraryName, EntryPoint = "voice_reverb_set_damping")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_reverb_set_damping(IntPtr handle, float damping);

    // ============================================
    // Delay Effect API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_delay_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_delay_create(int sampleRate, float delayMs, float feedback, float mix);

    [LibraryImport(LibraryName, EntryPoint = "voice_delay_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_delay_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_delay_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_delay_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_delay_set_time")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_delay_set_time(IntPtr handle, float delayMs);

    // ============================================
    // Pitch Shifter API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_pitch_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_pitch_create(int sampleRate, float semitones);

    [LibraryImport(LibraryName, EntryPoint = "voice_pitch_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_pitch_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_pitch_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_pitch_process(IntPtr handle, IntPtr input, int inSamples, IntPtr output, int outCapacity);

    [LibraryImport(LibraryName, EntryPoint = "voice_pitch_set_shift")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_pitch_set_shift(IntPtr handle, float semitones);

    // ============================================
    // Chorus API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_chorus_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_chorus_create(int sampleRate, float rate, float depth, float mix);

    [LibraryImport(LibraryName, EntryPoint = "voice_chorus_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_chorus_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_chorus_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_chorus_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    // ============================================
    // Flanger API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_flanger_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_flanger_create(int sampleRate, float rate, float depth, float feedback, float mix);

    [LibraryImport(LibraryName, EntryPoint = "voice_flanger_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_flanger_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_flanger_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_flanger_process(IntPtr handle, IntPtr input, IntPtr output, int samples);

    // ============================================
    // Time Stretcher API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_stretch_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_stretch_create(int sampleRate, int channels, float rate);

    [LibraryImport(LibraryName, EntryPoint = "voice_stretch_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_stretch_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_stretch_process")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_stretch_process(IntPtr handle, IntPtr input, int inSamples, IntPtr output, int outCapacity);

    [LibraryImport(LibraryName, EntryPoint = "voice_stretch_set_rate")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_stretch_set_rate(IntPtr handle, float rate);

    // ============================================
    // Watermark API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_watermark_embedder_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_watermark_embedder_create(int sampleRate, float strength);

    [LibraryImport(LibraryName, EntryPoint = "voice_watermark_embedder_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_watermark_embedder_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_watermark_embed_string")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_watermark_embed_string(IntPtr handle, IntPtr input, IntPtr output, int samples, IntPtr message);

    [LibraryImport(LibraryName, EntryPoint = "voice_watermark_detector_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_watermark_detector_create(int sampleRate);

    [LibraryImport(LibraryName, EntryPoint = "voice_watermark_detector_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_watermark_detector_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_watermark_has_watermark")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool voice_watermark_has_watermark(IntPtr handle, IntPtr samples, int numSamples);

    // ============================================
    // Comfort Noise API
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "voice_cng_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial IntPtr voice_cng_create(int sampleRate, int frameSize, float noiseLevel);

    [LibraryImport(LibraryName, EntryPoint = "voice_cng_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_cng_destroy(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "voice_cng_analyze")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_cng_analyze(IntPtr handle, IntPtr samples, int numSamples);

    [LibraryImport(LibraryName, EntryPoint = "voice_cng_generate")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial int voice_cng_generate(IntPtr handle, IntPtr output, int samples);

    [LibraryImport(LibraryName, EntryPoint = "voice_cng_set_level")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    public static partial void voice_cng_set_level(IntPtr handle, float levelDb);
}
